################################################################################
# Input configuration                                                          #
################################################################################

input:
  # Optional: input directory to use for fastq files (for local input files).
  dir: 'test/input'

  # Optional: configuration to use for remote (FTP) input files.
  # ftp:
  #   username: 'user'
  #   password: 'pass'


################################################################################
# Rule configuration                                                           #
################################################################################

# Single-end config for cutadapt.
cutadapt_se:
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    --minimum-length 20

# Paired-end config for cutadapt.
cutadapt_pe:
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    -q 20
    --minimum-length 20

hisat2:
  index: '/path/to/index'
  extra: ""
  threads: 10

sambamba_sort:
  extra: ''
  threads: 10

samtools_merge:
  extra: ''
  threads: 10

feature_counts:
  annotation: '/path/to/gtf'
  extra: ''
  threads: 5

multiqc:
  extra: ''

fastqc:
  extra: ''
